version: '3.7'

services:
  python-ai-jupyter:
    container_name: $CONTAINER_NAME
    image: $IMAGE
    pull_policy: always
    ports:
      - 8888:8888
    tty: false    
    volumes:
      - ${HOSTPATH_NOTEBOOKS}:/home/student/notebooks
      - ${HOSTPATH_PICS}:/home/student/pics